title: Muchen Sun's Course Note Template
description: Template repository for generating online course notes, based on GitHub Page and Jekyll
show_downloads: false
google_analytics: true
theme: jekyll-theme-cayman
mathjax: true
markdown: kramdown