title: Muchen Sun's Course Note Template
description: A General-Purpose Template for Online Course Notes
show_downloads: false
google_analytics: true
theme: jekyll-theme-cayman
mathjax: true
markdown: kramdown